### PR TITLE
Versionned dist file to ease sharing.

### PR DESCRIPTION
**Pull request by n1k0**
Versioning the output library file will help developers to toy around the API without having to build the lib setting up a full node environment.

### CODE REVIEW

**Comment by Natim** [comment]
Should we also provide an non uglified version?

**Comment by ametaireau** [comment]
Distributing these files on the github GH pages could also help!

**Comment by n1k0** [comment]
> Should we also provide an non uglified version?

Good idea. Like many projects do, I can come with at least two versions, minified with source maps for dev, and uglified + no source maps for production.

**Comment by n1k0** [comment]
I'm merging this. r=me

**Pull request merged**
