### PR TITLE
"ReferenceError: render is not defined" and a few typos in tutorial

### PR DESCRIPTION
**Pull request by ferjm**

### CODE REVIEW

**Comment by n1k0** [comment]
High five.

**Comment by Natim** [comment]
Should we also update https://github.com/mozilla-services/cliquetis/blob/master/demo/demo.js#L19?

**Comment by ferjm** [comment]
No, that's the final demo code. I removed that line cause at that point of the tutorial we don't have the `render` function defined.

**Comment by Natim** [comment]
Oh ok really good point. Thank you :+1:

**Pull request merged**
